name: SearchAgent
type: gradio-space
sdk: gradio

metadata:
  space_id: Chris4K/SearchAgent
  original_url: https://huggingface.co/spaces/Chris4K/SearchAgent

deploy:
  targets:
    - public-repo
    - huggingface

build:
  command: bash build.sh

test:
  command: echo "Tests not yet implemented"
